language: php

php: 7.1

install:
    - composer selfupdate --1
    - composer install

script:
    - vendor/bin/statie generate source
    - cp -f source/svatba/index.html.source output/svatba/index.html

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: output
    on:
        branch: master
